### ISSUE TITLE
Wrong example, not working

### ISSUE THREAD

**Issue by paologaleotti** [teamplayer3/ens160#15]
So im writing a firmware for STM32 in rust using this sensor, there is something wrong in the lib. Following the example (disabled std feature of course), once created the object it does not have all the fields and methods that it should:

![immagine](https://github.com/teamplayer3/ens160/assets/45665769/251ea74c-2e99-4241-85fc-4e6fb0486216)

**Comment by teamplayer3** [comment]
I tested it again and for me the auto-completion worked. You can try reloading the workspace in the rust-analyser extension. How do you create the i2c variable?

**Comment by paologaleotti** [comment]
It is possible that maybe my i2c is not compatible with the trait wanted by the library?

```rust

use stm32f1xx_hal::{
    i2c::{BlockingI2c, DutyCycle, Mode},
    prelude::*,
    stm32,
};

 let i2c = BlockingI2c::i2c1(
        dp.I2C1,
        (scl, sda),
        &mut afio.mapr,
        Mode::Fast {
            frequency: 400_000.Hz(),
            duty_cycle: DutyCycle::Ratio2to1,
        },
        clocks,
        1000,
        10,
        1000,
        1000,
    );
```

I'm just using the plain i2c from the stm32 HAL

**Comment by teamplayer3** [comment]
The hal you are using is using the old `embedded_hal` (`0.2.7`) version. `ens160` only supports > `1.0`. If this [PR](https://github.com/stm32-rs/stm32f1xx-hal/pull/416) gets merged it will work. Maybe you can ask for the state of it.

A workaround would be to write a wrapper around the i2c impl which impls the new `embedded-hal` traits in your project.

**Comment by paologaleotti** [comment]
Oh ok so its actually the stm32 HAL that is using an old embedded_hal? i actually did not notice that.

**Comment by teamplayer3** [comment]
Yes, that's correct. I hope the workaround will work, or the PR is merged soon.
