### ISSUE TITLE
feature   "no-std"

### ISSUE THREAD

**Issue by pdgilbert** [teamplayer3/ens160#6]
I am using `ens160` in `no-std` code.  It is not possible to specify 
```
ens160           = { git = "https://github.com/teamplayer3/ens160", features = ["no-std"], default-features = false }
```
in my `Cargo.toml` because the feature does not exist. The fix is to add
```
no-std = []
```
in the `[features]` section of the `ens160`  `Cargo.toml` file.

Also, I am getting the following warnings when `ens160`  compiles:
```
$ cargo build --no-default-features --target $TARGET --features $MCU,$HAL  --example ens160-co2-voc-iaq-display
   Compiling ens160 v0.6.0 (/home/paul/githubClones/ens160)
warning: field `0` is never read
 --> /home/paul/githubClones/ens160/src/error.rs:2:32
  |
2 | pub struct AirQualityConvError(pub(crate) u16);
  |            ------------------- ^^^^^^^^^^^^^^
  |            |
  |            field in this struct
  |
  = note: `AirQualityConvError` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  = note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
  |
2 | pub struct AirQualityConvError(());
  |                                ~~

   Compiling rust-integration-testing-of-examples v0.3.0 (/home/paul/githubClones/rust-integration-testing/dev-testing)
warning: `ens160` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 1.07s
```
and
```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

**Comment by teamplayer3** [comment]
> I am using ens160 in no-std code. It is not possible to specify

To use this crate in `no-std` you just have to set ` default-features = false` as you did. There is no `no-std` feature you have to set. More over, a `feature` should add stuff to a crate. If you want to specify a `no-std` context with feature `no-std` you would remove the standard library which is normally in prelude. The feature `std` will add the `std` support if needed. I designed the crate for `esp-idf-...` use, so I set the `std` env as default.

> Also, I am getting the following warnings when ens160 compiles:

Thanks, for reporting this. I fixed the warning.

> ```
>warning: the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2
>note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future- 
>incompatibilities --id 1`
>  ```

I think this warning belongs to another dependency you use. This crate hasn't the crate `nom` as dependency.

**Comment by pdgilbert** [comment]
Sorry I missed the obvious std logic, and thanks, I found the cause of the `nom`  `future-incompat` warning.
